DELETE http://localhost:3001/api/persons/4

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Testing morgan6",
    "number": "2323222"
}
###
GET http://localhost:3001/api/persons/